### PR TITLE
Remove is using redirect flag and new test cases with embedded web server

### PR DESCRIPTION
**Pull request by GuuBu**
After review with Dion, the finding is that the is_using_redirect can be safely remove it. Doing this will make the code more robust and easier to maintain.

### CODE REVIEW

**Review by dionysus1016 — APPROVED** [review]
please use visual code to format the code after review.

**Review by hzhang87 — APPROVED** [review]

**Review by cmb69 — COMMENTED** [review]
I have only had a look at the new test cases, and these look basically good to me. To support possible parallel test execution (`-jN` switch as of PHP 7.4.0), consider to add [`--CONFLICT--`](http://qa.php.net/phpt_details.php#conflicts_section) sections to the server tests. Nit: some of new test files seem to mix indentation with spaces and tabs.

**Comment by GuuBu** [comment]
Hi Christoph,
Thanks for checking. I've added the --CONFLICTS-- section in server_basic_pdo.phpt and server_basic_mysqil.phpt.  For the other two tests, there is no web server and the tests can go parallel with the same MySQL server, so I think there is no need to add the section, right?   In my understand, the parallel here means the tests can run in parallel, but the web server is still per singe process with single thread, is this right?   I've also updated the file format. Thanks a lot.
Best Regards,
Qianqian Bu

**Comment by cmb69** [comment]
Indeed, I see no problems when the other two tests run in parallel.

**Comment by GuuBu** [comment]
Thanks~ If no other suggestions, I'll close the PR then.

**Pull request merged**
